### ISSUE TITLE
control and options hotkeys

### ISSUE THREAD

**Issue by sergeyklochko** [gonzoua/MLSwitcher2#2]
Hello!

Any chance to single right ctrl and single right opt for hotkey for imac and macbooks?

It's faster than two keys together and very useful.

**Comment by gonzoua** [comment]
It's possible to implement single key switch, but unfortunately the API MLSwitcher uses does not differentiate between right/left key. So it's going to be either of controls and either of option keys

**Comment by sergeyklochko** [comment]
oh! it's not a problem at all. Can you do it, please?

**Comment by gonzoua** [comment]
Yes, I'll look into it this weekend

**Comment by sergeyklochko** [comment]
any chance?

**Comment by gonzoua** [comment]
I pushed a change with a fix. In order for it to work as expected you need to add MLSwitcher2 to the "Input Monitoring" list:

Preferences > Security & Privacy > Privacy tab > Input Monitoring menu item

**Comment by sergeyklochko** [comment]
Thank you. Do you have an intention to publish it to AppStore?
